package config

const EPSILON = 1e-3
const MAX_DEPTH = 10.0
const DEPTH_COLOR_DEGRADING_FACTOR = 0.9
const DEPTH_LIGHT_A_FACTOR = 0.9
const DEPTH_LIGHT_B_FACTOR = 0.1
const DEPTH_LIGHT_C_FACTOR = 0.1

const HEIGHT float32 = 1080
const WIDTH float32 = 1920
const AMBIENT_FACTOR = 0.3

const DEFAULT_FOV float32 = .4
const DEFAULT_ASPECT_RATIO float32 = WIDTH / HEIGHT
